### ISSUE TITLE
Flash announcement appearing w added padding on Library homepage

### ISSUE THREAD

**Issue by gyounger** [marcom-unimelb/unimelb-design-system#714] opened 2016-08-29 04:42 UTC
Hi, I tried to add a flash announcement to the Library homepage but it's appearing with 100px padding top:
![screen shot 2016-08-29 at 2 29 06 pm](https://cloud.githubusercontent.com/assets/16639864/18040956/a9486016-6df6-11e6-8c2a-d4bf986b68fb.png)
thanks
Gav

**Comment by axelboc** [comment] 2016-08-29 05:25
In theory, as long as the flash element is anywhere inside `<div role="main">`, it is supposed to be moved automatically between the header and the tabs. The fact that it appears above the header in your screenshots means that this behaviour is not working.

Can you please provide us with a snapshot of the markup you tried? Perhaps compare your markup to that of the search layout: https://web.unimelb.edu.au/layouts/search/ (source: https://web.unimelb.edu.au/layouts/search/source)?

**Comment by gyounger** [comment] 2016-08-29 05:34
hi @axelboc, 

<div class="flash flash--warning">
  <p><strong>Library E-journal and Database Outage!</strong> Library E-journal and Database Outage - Tuesday 30 August at 5.30pm, <a href="http://library.unimelb.edu.au/news-and-events/library-e-journal-and-database-outage">more details</a>.
  </p>
</div>

**Comment by gyounger** [comment] 2016-08-29 05:34
```
<div class="flash flash--warning">
  <p><strong>Library E-journal and Database Outage!</strong> Library E-journal and Database Outage - Tuesday 30 August at 5.30pm, <a href="http://library.unimelb.edu.au/news-and-events/library-e-journal-and-database-outage">more details</a>.
  </p>
</div>
```

**Comment by axelboc** [comment] 2016-08-29 06:08
Where does this markup sit in the page? Is it inside `<div role="main">`? Is the header with the search form actually a `header` element? Do you have test page set up somewhere I could take a look at?

**Comment by axelboc** [comment] 2016-08-29 06:09
Hmm and which browser are you using?

**Comment by axelboc** [comment] 2016-08-29 06:14
My guess is that you've put the `flash` element before the `header` in the markup. The documentation is not very clear on the matter, but it's a requirement for the header to remain the first child of `<div role="main">`.

**Comment by axelboc** [comment] 2016-08-29 06:34
Okay, I've improved the documentation. It will go live in the next release. Feel free to re-open the issue if that didn't solve it.

**Comment by gyounger** [comment] 2016-08-29 06:52
Ok thanks @axelboc I'll look through it and see whats up

**Comment by gyounger** [comment] 2016-09-01 02:40
@axelboc works fine on other library pages it seems, the library homepage has a lot of extra code for a custom header/search box. will see if can work out whats going on when have some additional time. 

![screen shot 2016-09-01 at 12 37 58 pm](https://cloud.githubusercontent.com/assets/16639864/18153488/2323e2a6-7041-11e6-9e02-ced9584dc1ab.png)

**Comment by axelboc** [comment] 2016-09-01 03:40
Okay, so the problem is that the `header` element on the homepage is not the first child of `div role="main"`:

![screen shot 2016-09-01 at 1 34 56 pm](https://cloud.githubusercontent.com/assets/2936402/18154570/1df7edec-7049-11e6-9cf5-c5f89aeaca05.png)

See how it's wrapped in an extra `div` and has a `script` tag and a `style` tag before it? Just remove the `div` wrapper, and try to move the `script` tag just before the closing `body` tag, and the `style` tag in the head of the page (if that's not possible, just move it after the `header`).

Note that there's a class for centring the text in the message, if you want. I think it's `flash--center`.

**Comment by gyounger** [comment] 2016-09-01 04:13
awesome thanks heaps for taking time to look at this @axelboc !

**Closed** 2016-09-01 04:24 UTC
Labels: documentation
