### ISSUE TITLE
class for PDFs

### ISSUE THREAD

**Issue by dkevey** [marcom-unimelb/unimelb-design-system#228] opened 2015-03-25 08:09 UTC
I may have missed this somewhere already in your documentation - and you may cringe at me asking - but a class (for PDF's) is needed please. 

Currently documents look like this, using class="icon document"
![current_style](https://cloud.githubusercontent.com/assets/1305804/6820344/1dd5b6b6-d322-11e4-83f8-03f89aa7fbfe.png)

I'll be migrating our faculty site to the new templates and yes, we have PDFs and yes they are necessary. 

This example shows where a program flyer (containing more information about student programs) is uploaded. Would be good if this style was similar to the "map" or "share" class please.

![program_flyer](https://cloud.githubusercontent.com/assets/1305804/6820357/3e2ad98c-d322-11e4-9b6f-ad4610b3b48c.png)

**Comment by tonyz** [comment] 2015-03-25 22:36
Agree with Donna, but to take it one step further, should we consider specific icons that represent the documents in question or is that messing with the design and style?

**Comment by herrweis** [comment] 2015-03-26 00:20
I agree, we need some form of visual mark that this will be a file to download. At this point I can't say if it is necessarily a document as icon or something else. Please bear with us as we haven't fully implemented the general icons yet. We are working on it, but it is a bit of a process as we don't work with icon fonts anymore (and it might be a bit different to implement in the future as to only writing a class on an element :-))

Thanks for the great input!

**Comment by waitingallday** [comment] 2015-03-26 11:02
Duplicate of #199

**Closed by waitingallday** 2015-03-26 11:02 UTC
Labels: duplicate
