### ISSUE TITLE
course structure page tables

### ISSUE THREAD

**Issue by dcollett** [marcom-unimelb/unimelb-design-system#299] opened 2015-08-21 06:57 UTC
When viewed on a mobile, the points cell & header go out of alignment. Examples:
http://web.unimelb.edu.au/layouts/course/#course-structure
http://www.unimelb.edu.au/online/clinicalteaching/masters/#course-structure

![screen shot 2015-08-21 at 4 56 13 pm](https://cloud.githubusercontent.com/assets/1088483/9402921/791c70b4-4825-11e5-9fb5-78230881a9e3.png)

**Comment by waitingallday** [comment] 2015-09-03 07:30
Argh yes, that will be caused by the mobile tables - will see what I can do about this.

**Comment by waitingallday** [comment] 2015-10-19 04:49
There's a fix for this going in the next deploy

**Comment by axelboc** [comment] 2015-10-19 04:54
Was that fixed with PR #322 as well?

**Comment by waitingallday** [comment] 2015-10-19 05:03
A fix was introduced back in https://github.com/marcom-unimelb/unimelb-design-system/commit/0c41fd275d66e59b5190e116d70c073fa161cadb#diff-cb3bba37dd7aaac543645735b0cfd46d but it needs another part on the bespoke end (will deploy shortly).

**Comment by waitingallday** [comment] 2015-10-19 06:28
Ah just noticed this isn't actually bespoke :( @dcollett In bespoke we added `mobile-wrap` to the classes on the degree container (should be `degree-plan` or `inner-nav-page` or both), this will prevent the mobile style "helper" from activating. There are a few minor CSS changes to restore the borderless style in the newly deployed v3.3.1 as well. Let me know if you need any help getting this working!

**Closed by waitingallday** 2015-10-19 06:28 UTC
Labels: bug

**Comment by dcollett** [comment] 2015-10-20 02:18
Thanks @waitingallday Chris Tan is looking after this site now and it looks like he's fixed it. The site in question was migrated out of Bespoke into a Webfarm site by Those Who Must Be Obeyed.

**Comment by waitingallday** [comment] 2015-10-20 03:08
:+1:
