### ISSUE TITLE
Injection/DOM manipulation is fragile

### ISSUE THREAD

**Issue by woowoowoo** [marcom-unimelb/unimelb-design-system#388] opened 2015-10-21 01:37 UTC
We are striking this with almost every new feature we attempt to enable in WordPress.

Almost all WordPress plugins use jQuery to update the DOM. When they do, it always seems to break the Design System injection. Presumably the two functions clash. Plugins seem to handle this between themselves, it's only the Design System that gets broken. I don't know how this can best be resolved, but the injection needs to be more robust, so that it can handle other DOM scripting on the page.

An example of the problem: http://blogs.unimelb.edu.au/qtraslate-test/2015/10/21/hello-world/ (use the simple password 'doc' to log in) where the menu icons don't work, the menu tray doesn't open and close correctly, and the social sharing icons (in the aside) aren't showing.

These exact same issues were being cause by the theme itself, which has to inject code to 'fix' some image markup problems. The theme developer worked out a way around that, but it's indicative of an issue that is going to keep happening, and needs to be resolved.

**Comment by waitingallday** [comment] 2015-10-21 01:51
The header icons (and the entire navigation) have failed due to a markup error in the document, this is a pretty common warning sign. If the markup is not correct, the system can't work. Javascript should never be used to manipulate markup in this way anyway, especially in a system like wordpress where the developer has complete control over how the page is rendered - the wordpress theme I wrote earlier this year did not need any javascript to run, please refer them to https://github.com/waitingallday/uom-wordpress-theme

**Comment by woowoowoo** [comment] 2015-10-21 04:05
Jason,
I can't see any errors in the original source, what do you mean? The only error I can find regards the insertion of <meta … /> inside an <li> in the breadcrumbs, but that appears to be correct as far as the Design System is concerned.
If it's a problem with the underlying theme, I'd be confident we can get that fixed.

**Comment by waitingallday** [comment] 2015-10-21 04:41
There is no error in using `meta` inside `li` - this is the recommended way of using microdata with schema.org, as suggested by @pipgrinblat http://schema.org/BreadcrumbList

At a quick glance, there are just a couple of minor markup problems - an `li` in the local nav isn't closed, and the two page wrappers are not closed - but that's not causing the trouble. I tracked it back to the "language" links - an `a` element doesn't require a href attribute, but the local nav *does* require it, or it fails, as it did here. When the local nav fails it stops the system from continuing, so the footer & icons are never rendered. A quick fix will be to add `href="#"` on those links.

Also, I would suggest that you not use sub-navigation in the .meta links, the purpose of this container is only for a few popular links that don't fit within the navigation hierarchy.

**Comment by herrweis** [comment] 2015-10-21 04:49
Coming from a country where we frequently (approx. 90%) built websites in multiple languages, I want to add something as well: A language switch that relies on labels to reveal the available options should be avoided at all costs. The problem is that they don't work. Imagine I would only speak German. I would not know that there is an option for my language in the submenu because I would not be able to understand the word "Languages". Language options should always be visible. (and ideally pre-chosen according to the browser language — not geo-targeting)

**Comment by woowoowoo** [comment] 2015-10-21 04:52
Yes,
the plugin does all the browser preference reading stuff, it's quite comprehensive, but if all else fails, a manual switch is a useful thing.

**Comment by woowoowoo** [comment] 2015-10-21 04:55
hmm - ok. I'm only going on the output of an automated validator regarding the meta inside li issue. There are always varying opinions on those as 'errors'.

The lack of an href attribute is something concrete I can go back to the plugin developer with, so that's great. Thanks.

As for the sub menu in the meta links - yes - it's just that the plugin allows a site owner to do it, so, not something I can prevent happening, even if it's not ideal.

**Comment by woowoowoo** [comment] 2015-10-21 05:23
Have alerted the plugin developers to the issue. Also, found an alternative way of switching languages using a widget instead of the menu, so that's a workaround for now. :-)

**Comment by waitingallday** [comment] 2015-10-27 06:02
Thanks Andrew, closing this one for now.

**Closed by waitingallday** 2015-10-27 06:02 UTC
Labels: wontfix
