### ISSUE TITLE
Fix to word wrapping in the Search layout on mobile

### ISSUE THREAD

**Issue by chazbatrouney** [marcom-unimelb/unimelb-design-system#437] opened 2015-11-09 04:36 UTC
When searching using the new search layout some words wrap incorrectly.  The following styles have been implemented to correct this, but needs to be checked and incorporated into the code base so overrides are not required in the header.

```
.result-item p.url, .result-item a[ctype="sitesearch"].f {

	  overflow-wrap: break-word;
	  word-wrap: break-word;

	  -ms-word-break: break-all;
	  /* This is the dangerous one in WebKit, as it breaks things wherever */
	  word-break: break-all;
	  /* Instead use this non-standard one: */
	  word-break: break-word;

	  /* Adds a hyphen where the word breaks, if supported (No Blink) */
	  -ms-hyphens: auto;
	  -moz-hyphens: auto;
	  -webkit-hyphens: auto;
	  hyphens: auto;
   }
```

**Comment by chazbatrouney** [comment] 2015-11-13 00:23
This problem has been rectified in a previous releases of the DDS

**Comment by chazbatrouney** [comment] 2015-11-16 06:23
Problem is back :(

**Comment by axelboc** [comment] 2015-11-16 21:48
Will be fixed with the refactoring of the search results #450

**Comment by chazbatrouney** [comment] 2016-01-11 06:06
@axelboc I sent an email about this last year as there still seems to be some problems with the wrapping on certain search terms when on mobile. If you visit beta-search.unimelb.edu.au and search for "isis" you will see the problem. All the fixes we went through to resolve have been applied to my knowledge so unsure why this is still occurring?

**Comment by axelboc** [comment] 2016-01-11 22:03
Ah yeah I see it! The markup is fine; it's just another issue with the `with-aside` layout. I'll work on it today.

**Comment by axelboc** [comment] 2016-01-11 22:28
Scratch that - even though the layout shouldn't behave like that, the root cause is indeed the wrapping of the URL. I can fix it without the need for a markup change.

**Closed** 2016-01-29 00:30 UTC
Labels: bug
